# Generated by Django 4.1 on 2024-11-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=6)),
                ('Descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Sexo',
            },
        ),
    ]
